version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      all-deps:
        patterns:
          - '*'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(deps):'
