/**
 * @file Shell completion script generators for bash, zsh, and fish.
 * Each generator embeds CLI commands, flags, and agent-name lookup logic
 * so the resulting script works standalone after being sourced.
 */
import { CLI_COMMANDS, CLI_FLAGS, COMMANDS_WITH_AGENT_ARG } from './args';
import { AGENT_STATE_BASE } from '@agntk/core';

export type Shell = 'bash' | 'zsh' | 'fish';

/**
 *
 * @param shell
 */
export function generateCompletionScript(shell: Shell): string {
  switch (shell) {
    case 'bash':
      return generateBash();
    case 'zsh':
      return generateZsh();
    case 'fish':
      return generateFish();
  }
}

/*
 * ============================================================================
 * Bash
 * ============================================================================
 */

/**
 *
 */
function generateBash(): string {
  const commands = CLI_COMMANDS.join(' ');
  const flags = CLI_FLAGS.join(' ');
  const agentCmds = COMMANDS_WITH_AGENT_ARG.join('|');
  const agentsPath = `$HOME/${AGENT_STATE_BASE}`;

  return `# agntk bash completion — generated by "agntk completions bash"
# Add to ~/.bashrc: eval "$(agntk completions bash)"

_agntk_completions() {
  local cur prev words cword
  _init_completion || return

  local commands="${commands}"
  local flags="${flags}"

  case "$prev" in
    ${agentCmds})
      # Complete agent names from ~/.agntk/agents/
      local agents_dir="${agentsPath}"
      if [[ -d "$agents_dir" ]]; then
        COMPREPLY=( $(compgen -W "$(ls "$agents_dir" 2>/dev/null)" -- "$cur") )
      fi
      return
      ;;
    completions)
      COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
      return
      ;;
    install|uninstall|evaluate)
      # File completion for capability management commands
      COMPREPLY=( $(compgen -f -X '!*.md' -- "$cur") )
      return
      ;;
    -n|--name)
      # Complete agent names for --name flag
      local agents_dir="${agentsPath}"
      if [[ -d "$agents_dir" ]]; then
        COMPREPLY=( $(compgen -W "$(ls "$agents_dir" 2>/dev/null)" -- "$cur") )
      fi
      return
      ;;
    --workspace)
      # Directory completion
      _filedir -d
      return
      ;;
    --instructions|--max-steps)
      # No completion for value args
      return
      ;;
  esac

  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
    return
  fi

  # Default: complete commands
  COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
}

complete -F _agntk_completions agntk
`;
}

/*
 * ============================================================================
 * Zsh
 * ============================================================================
 */

/**
 *
 */
function generateZsh(): string {
  const agentsPath = `$HOME/${AGENT_STATE_BASE}`;

  const commandDescs = [
    'list:List all known agents and their status',
    'info:Show agent details',
    'delete:Permanently delete an agent and its memory',
    'stop:Send SIGTERM to a running agent process',
    'clean:Interactively prune stale or unused agents',
    'completions:Output shell completion script',
    'install:Install a capability into the harness',
    'uninstall:Remove an installed capability',
    'evaluate:Validate a capability file',
  ];

  return `#compdef agntk
# agntk zsh completion — generated by "agntk completions zsh"
# Add to ~/.zshrc: eval "$(agntk completions zsh)"

_agntk() {
  local -a commands
  commands=(
${commandDescs.map((d) => `    '${d}'`).join('\n')}
  )

  _arguments -C \\
    '(-n --name)'{-n,--name}'[Agent name]:name:->agents' \\
    '--instructions[System prompt override]:text:' \\
    '(-i --interactive)'{-i,--interactive}'[Start interactive REPL]' \\
    '--workspace[Working directory]:path:_directories' \\
    '--verbose[Print full tool arguments and output]' \\
    '(-q --quiet)'{-q,--quiet}'[Suppress decorations]' \\
    '--max-steps[Limit tool-loop iterations]:number:' \\
    '(-v --version)'{-v,--version}'[Print version]' \\
    '(-h --help)'{-h,--help}'[Print help]' \\
    '1:command:->command' \\
    '2:argument:->argument' \\
    '*::prompt:' && return

  case "$state" in
    command)
      _describe 'command' commands
      ;;
    argument)
      case "$words[2]" in
        info|delete|stop)
          local agents_dir="${agentsPath}"
          if [[ -d "$agents_dir" ]]; then
            local -a agent_names
            agent_names=( $(ls "$agents_dir" 2>/dev/null) )
            _describe 'agent' agent_names
          fi
          ;;
        completions)
          _values 'shell' bash zsh fish
          ;;
        install|uninstall|evaluate)
          _files -g '*.md'
          ;;
      esac
      ;;
    agents)
      local agents_dir="${agentsPath}"
      if [[ -d "$agents_dir" ]]; then
        local -a agent_names
        agent_names=( $(ls "$agents_dir" 2>/dev/null) )
        _describe 'agent' agent_names
      fi
      ;;
  esac
}

compdef _agntk agntk
`;
}

/*
 * ============================================================================
 * Fish
 * ============================================================================
 */

/**
 *
 */
function generateFish(): string {
  const agentsPath = `$HOME/${AGENT_STATE_BASE}`;

  const commandEntries: Array<[string, string]> = [
    ['list', 'List all known agents and their status'],
    ['info', 'Show agent details'],
    ['delete', 'Permanently delete an agent and its memory'],
    ['stop', 'Send SIGTERM to a running agent process'],
    ['clean', 'Interactively prune stale or unused agents'],
    ['completions', 'Output shell completion script'],
    ['install', 'Install a capability into the harness'],
    ['uninstall', 'Remove an installed capability'],
    ['evaluate', 'Validate a capability file'],
  ];

  const flagEntries: Array<{ short?: string; long: string; desc: string }> = [
    { short: 'n', long: 'name', desc: 'Agent name' },
    { long: 'instructions', desc: 'System prompt override' },
    { short: 'i', long: 'interactive', desc: 'Start interactive REPL' },
    { long: 'workspace', desc: 'Working directory' },
    { long: 'verbose', desc: 'Print full tool output' },
    { short: 'q', long: 'quiet', desc: 'Suppress decorations' },
    { long: 'max-steps', desc: 'Limit tool-loop iterations' },
    { short: 'v', long: 'version', desc: 'Print version' },
    { short: 'h', long: 'help', desc: 'Print help' },
  ];

  const lines: string[] = [
    '# agntk fish completion — generated by "agntk completions fish"',
    '# Add to fish: agntk completions fish | source',
    '# Or save to: ~/.config/fish/completions/agntk.fish',
    '',
    '# Disable file completions by default',
    'complete -c agntk -f',
    '',
    '# Helper: list agent names',
    `function __agntk_agents`,
    `  set -l dir "${agentsPath}"`,
    '  if test -d $dir',
    '    ls $dir 2>/dev/null',
    '  end',
    'end',
    '',
    '# Subcommands (when no subcommand is given yet)',
  ];

  for (const [name, desc] of commandEntries) {
    lines.push(
      `complete -c agntk -n "not __fish_seen_subcommand_from ${commandEntries.map(([n]) => n).join(' ')}" -a "${name}" -d "${desc}"`,
    );
  }

  lines.push('');
  lines.push('# Flags');
  for (const flag of flagEntries) {
    const parts = ['complete -c agntk'];
    if (flag.short) parts.push(`-s ${flag.short}`);
    parts.push(`-l ${flag.long}`);
    parts.push(`-d "${flag.desc}"`);
    lines.push(parts.join(' '));
  }

  lines.push('');
  lines.push('# Agent name completion for info/delete/stop');
  for (const cmd of COMMANDS_WITH_AGENT_ARG) {
    lines.push(
      `complete -c agntk -n "__fish_seen_subcommand_from ${cmd}" -a "(__agntk_agents)" -d "Agent name"`,
    );
  }

  lines.push('');
  lines.push('# Shell completion for completions command');
  lines.push(
    'complete -c agntk -n "__fish_seen_subcommand_from completions" -a "bash zsh fish" -d "Shell type"',
  );

  lines.push('');
  return lines.join('\n');
}
